# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        make install
        make build

    - name: Run linter
      run: make lint
      
    - name: Deploy
      run: |
        curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.TRIGGER_DEPLOY_KEY }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Valentina-Vasileva/frontend-project-lvl3/actions/workflows/docker-build-deploy.yml/dispatches -d '{"ref":"main","inputs":{}' 
